/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Color { 'hex' : string, 'name' : string }
export interface Customer {
  'id' : string,
  'customerType' : CustomerType,
  'owner' : Principal,
  'city' : [] | [string],
  'postalCode' : [] | [string],
  'name' : string,
  'businessName' : [] | [string],
  'state' : [] | [string],
  'addressLine1' : [] | [string],
  'contactNumber' : string,
}
export interface CustomerForm {
  'customerType' : CustomerType,
  'city' : [] | [string],
  'postalCode' : [] | [string],
  'name' : string,
  'businessName' : [] | [string],
  'state' : [] | [string],
  'addressLine1' : [] | [string],
  'contactNumber' : string,
}
export type CustomerType = { 'retail' : null } |
  { 'direct' : null } |
  { 'wholesale' : null };
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Product {
  'id' : bigint,
  'retailPrice' : bigint,
  'owner' : Principal,
  'availableQuantity' : bigint,
  'name' : string,
  'wholesalePrice' : bigint,
  'description' : string,
  'stockCount' : bigint,
  'madeToOrder' : boolean,
  'directPrice' : bigint,
  'colors' : Array<Color>,
  'visibility' : ProductVisibility,
  'images' : Array<ExternalBlob>,
}
export interface ProductForm {
  'retailPrice' : bigint,
  'availableQuantity' : bigint,
  'name' : string,
  'wholesalePrice' : bigint,
  'description' : string,
  'stockCount' : bigint,
  'madeToOrder' : boolean,
  'directPrice' : bigint,
  'colors' : Array<Color>,
  'visibility' : ProductVisibility,
  'images' : Array<ExternalBlob>,
}
export type ProductVisibility = { 'all' : null } |
  { 'wholesaleOnly' : null } |
  { 'retailOnly' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeaverProfile {
  'logo' : ExternalBlob,
  'name' : string,
  'address' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCustomer' : ActorMethod<[string, CustomerForm], undefined>,
  'addProduct' : ActorMethod<[ProductForm], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateWeaverProfile' : ActorMethod<
    [string, ExternalBlob, string],
    undefined
  >,
  'explicitSetStockCount' : ActorMethod<[bigint, bigint], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerProfile' : ActorMethod<[], [] | [WeaverProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCatalogByCustomerType' : ActorMethod<[CustomerType], Array<Product>>,
  'getCatalogByWeaver' : ActorMethod<[Principal, CustomerType], Array<Product>>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMyProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint, Principal], [] | [Product]>,
  'getPublicCatalogNonAuthenticated' : ActorMethod<
    [Principal, CustomerType],
    Array<Product>
  >,
  'getPublicProduct' : ActorMethod<[bigint, Principal], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCustomer' : ActorMethod<[string], undefined>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'toggleOutOfStock' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductForm], undefined>,
  'updateProductQuantity' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];