/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CustomerType = IDL.Variant({
  'retail' : IDL.Null,
  'direct' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const CustomerForm = IDL.Record({
  'customerType' : CustomerType,
  'city' : IDL.Opt(IDL.Text),
  'postalCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'addressLine1' : IDL.Opt(IDL.Text),
  'contactNumber' : IDL.Text,
});
export const Color = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
export const ProductVisibility = IDL.Variant({
  'all' : IDL.Null,
  'wholesaleOnly' : IDL.Null,
  'retailOnly' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductForm = IDL.Record({
  'retailPrice' : IDL.Nat,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Nat,
  'description' : IDL.Text,
  'madeToOrder' : IDL.Bool,
  'directPrice' : IDL.Nat,
  'colors' : IDL.Vec(Color),
  'visibility' : ProductVisibility,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'customerType' : CustomerType,
  'owner' : IDL.Principal,
  'city' : IDL.Opt(IDL.Text),
  'postalCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'addressLine1' : IDL.Opt(IDL.Text),
  'contactNumber' : IDL.Text,
});
export const WeaverProfile = IDL.Record({
  'logo' : ExternalBlob,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'retailPrice' : IDL.Nat,
  'owner' : IDL.Principal,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Nat,
  'description' : IDL.Text,
  'madeToOrder' : IDL.Bool,
  'directPrice' : IDL.Nat,
  'colors' : IDL.Vec(Color),
  'visibility' : ProductVisibility,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCustomer' : IDL.Func([IDL.Text, CustomerForm], [], []),
  'addProduct' : IDL.Func([ProductForm], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateWeaverProfile' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(WeaverProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogByCustomerType' : IDL.Func(
      [CustomerType],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getCatalogByWeaver' : IDL.Func(
      [IDL.Principal, CustomerType],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Opt(Product)],
      ['query'],
    ),
  'getPublicCatalogNonAuthenticated' : IDL.Func(
      [IDL.Principal, CustomerType],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getPublicProduct' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Opt(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCustomer' : IDL.Func([IDL.Text], [], []),
  'removeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleOutOfStock' : IDL.Func([IDL.Nat], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductForm], [], []),
  'updateProductQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CustomerType = IDL.Variant({
    'retail' : IDL.Null,
    'direct' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const CustomerForm = IDL.Record({
    'customerType' : CustomerType,
    'city' : IDL.Opt(IDL.Text),
    'postalCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'addressLine1' : IDL.Opt(IDL.Text),
    'contactNumber' : IDL.Text,
  });
  const Color = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
  const ProductVisibility = IDL.Variant({
    'all' : IDL.Null,
    'wholesaleOnly' : IDL.Null,
    'retailOnly' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductForm = IDL.Record({
    'retailPrice' : IDL.Nat,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Nat,
    'description' : IDL.Text,
    'madeToOrder' : IDL.Bool,
    'directPrice' : IDL.Nat,
    'colors' : IDL.Vec(Color),
    'visibility' : ProductVisibility,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'customerType' : CustomerType,
    'owner' : IDL.Principal,
    'city' : IDL.Opt(IDL.Text),
    'postalCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'addressLine1' : IDL.Opt(IDL.Text),
    'contactNumber' : IDL.Text,
  });
  const WeaverProfile = IDL.Record({
    'logo' : ExternalBlob,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'retailPrice' : IDL.Nat,
    'owner' : IDL.Principal,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Nat,
    'description' : IDL.Text,
    'madeToOrder' : IDL.Bool,
    'directPrice' : IDL.Nat,
    'colors' : IDL.Vec(Color),
    'visibility' : ProductVisibility,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCustomer' : IDL.Func([IDL.Text, CustomerForm], [], []),
    'addProduct' : IDL.Func([ProductForm], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateWeaverProfile' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(WeaverProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogByCustomerType' : IDL.Func(
        [CustomerType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getCatalogByWeaver' : IDL.Func(
        [IDL.Principal, CustomerType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Opt(Product)],
        ['query'],
      ),
    'getPublicCatalogNonAuthenticated' : IDL.Func(
        [IDL.Principal, CustomerType],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getPublicProduct' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Opt(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCustomer' : IDL.Func([IDL.Text], [], []),
    'removeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleOutOfStock' : IDL.Func([IDL.Nat], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductForm], [], []),
    'updateProductQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };